spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drivehub_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
app:
  jwt:
    secret: DriveHubSuperSecretKey_ChangeThis_12345678901234567890
    access-expiration: 900000        # 15 minutes (ms)
    refresh-expiration: 604800000    # 7 days (ms)